name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Auth Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASS}}

    - name: Build Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          pipeline-kub-ocean:v1
          pipeline-kub-ocean:latest
          
  
