name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Auth Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PASS}}

    - name: Build Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: 
          fehdocker/pipeline-kub-ocean:latest
  
  CD: 
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Define context kub
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Deploy kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          images: fehdocker/pipeline-kub-ocean:latest
          manifest: |
            k8s/deployment.yaml

 
          
  
